Use Ruby 2.6 Docker image in CircleCI job
With the 2.5 image, we get the following error:

    ERROR:  Error installing fpm:
            The last version of public_suffix (>= 2.0.2, < 6.0) to support your Ruby & RubyGems was 4.0.7. Try installing it with `gem install public_suffix -v 4.0.7` and then running the current command again
            public_suffix requires Ruby version >= 2.6. The current ruby version is 2.5.9.229.